# Generated by Django 6.0 on 2025-12-31 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('verdict', models.CharField(choices=[('Pending', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='Pending', max_length=50)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('runtime', models.FloatField(null=True)),
                ('memory', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
        ),
    ]
