# Generated by Django 6.0 on 2025-12-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='runtime',
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_kb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='runtime_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=50),
        ),
    ]
