# Generated by Django 6.0 on 2025-12-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.IntegerField(default=256, help_text='Memory limit in MB'),
        ),
        migrations.AddField(
            model_name='problem',
            name='reference_solution',
            field=models.JSONField(default=dict, help_text='Trusted solution used to generate expected outputs'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit_ms',
            field=models.IntegerField(default=2000, help_text='Time limit in milliseconds'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.IntegerField(default=0, help_text='Execution order'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='driver_code',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(help_text='Expected output (generated from reference solution)'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(help_text='Raw input data for the test case'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden test cases only used in Submit mode'),
        ),
    ]
