# Generated by Django 6.0 on 2025-12-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_testcase_options_problem_memory_limit_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.CharField(blank=True, help_text='Email or ID of the creator', max_length=255, null=True),
        ),
    ]
