# Generated by Django 6.0 on 2025-12-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Flag to identify problems created by AI'),
        ),
    ]
