# Generated by Django 6.0 on 2026-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_constraints_problem_input_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Explanation for the test case'),
        ),
    ]
